services:
  nextjs:
    build: ./nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongo
      - python-ai
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/rpgdb
      - PYTHON_AI_URL=http://python-ai:8000
      - JWT_SECRET=$(JWT_SECRET)
    networks:
      - rpgnetwork

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - rpgnetwork

  python-ai:
    build: ./python-ai
    ports:
      - "8000:8000"
    volumes:
      - ./python-ai:/app
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rpgdb
      - PYTHONPATH=/app
    networks:
      - rpgnetwork

volumes:
  mongodata:

networks:
  rpgnetwork: